/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.16
 * Generated at: 2017-09-20 08:47:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.addrbook;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import jspbook.addrbook.*;
import java.util.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("jspbook.addrbook");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      jspbook.addrbook.AddrBook addrbook = null;
      addrbook = (jspbook.addrbook.AddrBook) _jspx_page_context.getAttribute("addrbook", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (addrbook == null){
        addrbook = new jspbook.addrbook.AddrBook();
        _jspx_page_context.setAttribute("addrbook", addrbook, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      jspbook.addrbook.AddrBean addrbean = null;
      addrbean = (jspbook.addrbook.AddrBean) _jspx_page_context.getAttribute("addrbean", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (addrbean == null){
        addrbean = new jspbook.addrbook.AddrBean();
        _jspx_page_context.setAttribute("addrbean", addrbean, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');

	ArrayList<AddrBook> list = addrbean.getDBList();
	String[] pic_list = new String[list.size()];
	Iterator<AddrBook> it = list.iterator();
	for (int i = 0; it.hasNext(); i++) {
		pic_list[i] = it.next().getAb_picture();
	}
	String memberId = (String) session.getAttribute("memberid");
	
	AddrBook user_pic=addrbean.getDB(memberId);
	String user_pic2=user_pic.getAb_picture();

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>MyHompage</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"Hompage.css\" type=\"text/css\" media=\"screen\" />\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write(".img {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t\t<li class=\"home\"><a href=\"index.jsp\"><img src=\"homeIcon.png\"\r\n");
      out.write("\t\t\t\theight=\"48\" width=\"48\" /></a></li>\r\n");
      out.write("\t\t");

			if (memberId != null) {
		
      out.write("\r\n");
      out.write("\t\t<li><a href=\"logout.jsp\">로그아웃</a></li>\r\n");
      out.write("\t\t");

			} else {
		
      out.write("\r\n");
      out.write("\t\t<li><a href=\"login_form.html\">로그인</a></li>\r\n");
      out.write("\t\t");

			}
		
      out.write("\r\n");
      out.write("\t\t<li><a href=\"addrbook_control.jsp?action=list\">회원리스트</a></li>\r\n");
      out.write("\t\t<li><a href=\"addrbook_form.jsp\">회원가입</a></li>\r\n");
      out.write("\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<div class=\"gate\">\r\n");
      out.write("\t\t<div class=\"winner\">The Winner Takes It All</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"main_container\">\r\n");
      out.write("\t\t\t<div class=\"picture\">\r\n");
      out.write("\t\t\t\t");

					try {
						
						if (list != null) {
							if (memberId!=null) {
							out.print("다른 사용자님들의 프로필 사진입니다.");
								for (int i = 0; i < pic_list[i].length(); i++) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.print(pic_list[i]);
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

								}
							}
						}
					} catch (Exception e) {
						System.out.print(e);
					}
				
      out.write("\r\n");
      out.write("\t\t\t\t");

					if(user_pic.getAb_picture()!=null){
						out.print(user_pic.getAb_name()+"님이 올리신 프로필 사진입니다.");
				
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.print(user_pic.getAb_picture() );
      out.write("\">\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- <div class=\"gradient1\">Copyright(c)2017 이혁제 All rights reserved.\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
